@extends('app')
@section('content')
	@include('partials.pages.home.section1')
	@include('partials.pages.home.section2')
	@include('partials.pages.home.section3')
	@include('partials.pages.home.section4')
	@include('partials.pages.home.section5')
	@include('partials.pages.home.section6')
@endsection